### ISSUE TITLE
travis testing failed on DataExtensionTests.testFetchCounts

### ISSUE THREAD

**Issue by jackyq2015** [jackyq2015/OpenRefine#1]
Version: commit 98f945b  
  
 [testng] FAILED: testFetchCounts
   [testng] java.lang.NullPointerException
   [testng] 	at com.google.refine.tests.recon.DataExtensionTests.testFetchCounts(DataExtensionTests.java:216)
   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   [testng] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [testng] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [testng] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
   [testng] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
   [testng] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
   [testng] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
   [testng] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
   [testng] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
   [testng] 	at org.testng.TestRunner.privateRun(TestRunner.java:767)
   [testng] 	at org.testng.TestRunner.run(TestRunner.java:617)
   [testng] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
   [testng] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
   [testng] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
   [testng] 	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
   [testng] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
   [testng] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
   [testng] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
   [testng] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
   [testng] 	at org.testng.TestNG.run(TestNG.java:1031)
   [testng] 	at org.testng.TestNG.privateMain(TestNG.java:1338)
   [testng] 	at org.testng.TestNG.main(TestNG.java:1307)
   [testng] 
   [testng] 
   [testng] ===============================================
   [testng]     tests
   [testng]     Tests run: 226, Failures: 1, Skips: 0
   [testng] ===============================================

**Comment by jackyq2015** [comment]
caused by org.json upgrade. solved
